name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: Update Composer to latest version
        run: sudo composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction

      - name: Run lint
        run: composer lint
